<template>
  <div>
    <SiteToolBar></SiteToolBar>
    <v-content>
      <v-container grid-list-md>
        <v-layout row wrap justify-center align-start>
          <v-flex v-for="msg in msgs" :key="msg.title" xs12>
            <v-container fluid>
              <v-layout row wrap>
                <v-flex xs12>
                  <div class="title font-weight-medium">
                    {{ msg.title }}
                  </div>
                </v-flex>
                <v-flex xs12>
                  <read-more
                    more-str="read more"
                    :text="msg.text"
                    link="#"
                    less-str="read less"
                    :max-chars="200"
                  ></read-more>
                </v-flex>
              </v-layout>
            </v-container>
          </v-flex>
        </v-layout>
      </v-container>
    </v-content>
    <TheFooter> </TheFooter>
  </div>
</template>
<script>
import SiteToolBar from "@/components/SiteToolBar.vue";
import TheFooter from "@/components/TheFooter.vue";

export default {
  name: "protectionmonitoring",
  components: {
    SiteToolBar,
    TheFooter
  },
  data() {
    return {
      msgs: [
        {
          title: "Title 1",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 2",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 3",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 4",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 5",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 6",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 7",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 8",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        }
      ]
    };
  }
};
</script>
<style lang="scss" scoped></style>
