<template>
  <v-content>
    <v-container grid-list-xl fluid>
      <v-layout row wrap jalign-center justify-center fill-height>
        <v-flex d-flex xs12>
          <v-card>
            <v-card-text>
              <read-more
                more-str="read more"
                :text="lorem"
                link="#"
                less-str="read less"
                :max-chars="1200"
                class="full"
              ></read-more>
            </v-card-text>
          </v-card>
        </v-flex>
        <v-flex d-flex v-for="msg in msgs" :key="msg.title" xs12>
          <v-layout row wrap>
            <v-flex d-flex xs12 class="text-xs-center accent ">
              <div class="title font-weight-medium white--text">
                {{ msg.title }}
              </div>
            </v-flex>
            <v-flex d-flex xs12>
              <read-more
                more-str="read more"
                :text="msg.text"
                link="#"
                less-str="read less"
                :max-chars="800"
                class="full"
              ></read-more>
            </v-flex>
            <v-flex d-flex xs12><v-divider></v-divider> </v-flex>
          </v-layout>
        </v-flex>
      </v-layout>
    </v-container>
  </v-content>
</template>
<script>
export default {
  name: "protectionmonitoring",
  components: {},
  data() {
    return {
      lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Facilisi cras fermentum odio eu feugiat. Adipiscing at in tellus integer. Magna sit amet purus gravida quis blandit turpis cursus. Sit amet facilisis magna etiam tempor. Lacus viverra vitae congue eu consequat. Egestas dui id ornare arcu odio ut sem nulla. Id eu nisl nunc mi. Varius quam quisque id diam vel quam elementum pulvinar etiam. Egestas sed sed risus pretium quam. Vitae elementum curabitur vitae nunc. Sed arcu non odio euismod lacinia at quis risus.
Aliquet lectus proin nibh nisl. Amet mauris commodo quis imperdiet massa. Tempor commodo ullamcorper a lacus vestibulum sed. Vestibulum morbi blandit cursus risus at. Tempor orci dapibus ultrices in. Nunc consequat interdum varius sit amet mattis. Consectetur a erat nam at lectus urna duis. Sit amet volutpat consequat mauris nunc congue nisi. Nunc id cursus metus aliquam eleifend mi in nulla. Porttitor leo a diam sollicitudin. Scelerisque in dictum non consectetur a. Nulla pharetra diam sit amet nisl suscipit. Tortor consequat id porta nibh.
Urna nunc id cursus metus aliquam eleifend mi in nulla. Non tellus orci ac auctor augue. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Amet est placerat in egestas erat imperdiet sed. Eget gravida cum sociis natoque. Nunc eget lorem dolor sed viverra ipsum. Et leo duis ut diam quam nulla porttitor massa. Faucibus interdum posuere lorem ipsum dolor sit amet. Mus mauris vitae ultricies leo. Morbi blandit cursus risus at ultrices mi. Habitasse platea dictumst quisque sagittis purus sit. Enim eu turpis egestas pretium aenean pharetra magna. Ut sem viverra aliquet eget sit amet tellus cras. Sagittis aliquam malesuada bibendum arcu vitae elementum. Vulputate sapien nec sagittis aliquam malesuada bibendum. Gravida quis blandit turpis cursus. Sed blandit libero volutpat sed cras. Sem viverra aliquet eget sit amet tellus cras. Mauris rhoncus aenean vel elit scelerisque.
Elit pellentesque habitant morbi tristique senectus et netus. Ornare arcu odio ut sem nulla pharetra diam sit. Quisque egestas diam in arcu cursus euismod quis viverra nibh. Platea dictumst quisque sagittis purus. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. In nibh mauris cursus mattis molestie a. Convallis aenean et tortor at risus. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Tempus imperdiet nulla malesuada pellentesque. Mauris cursus mattis molestie a. Tellus orci ac auctor augue mauris augue. Aenean et tortor at risus viverra adipiscing at in. Ultrices tincidunt arcu non sodales neque. Volutpat sed cras ornare arcu. Elementum eu facilisis sed odio morbi quis. Sit amet consectetur adipiscing elit pellentesque. Turpis cursus in hac habitasse. Pellentesque elit eget gravida cum.
Non consectetur a erat nam at lectus urna duis convallis. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Et leo duis ut diam quam nulla porttitor. Vitae congue mauris rhoncus aenean vel. Magna fermentum iaculis eu non diam phasellus. Turpis in eu mi bibendum neque egestas congue quisque. Massa tempor nec feugiat nisl pretium fusce id velit ut. Quis risus sed vulputate odio ut enim. Mattis rhoncus urna neque viverra justo. Odio morbi quis commodo odio. Massa id neque aliquam vestibulum morbi. Auctor eu augue ut lectus. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Velit laoreet id donec ultrices tincidunt arcu non. Sit amet consectetur adipiscing elit pellentesque habitant. Vitae proin sagittis nisl rhoncus mattis rhoncus urna.`,
      msgs: [
        {
          title: "Title 1",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 2",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 3",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 4",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 5",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 6",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 7",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        },
        {
          title: "Title 8",
          text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor morbi non arcu risus. Etiam tempor orci eu lobortis elementum nibh tellus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Quam adipiscing vitae proin sagittis nisl. Amet volutpat consequat mauris nunc congue nisi vitae. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ligula ullamcorper malesuada proin libero nunc consequat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Congue eu consequat ac felis. Amet facilisis magna etiam tempor orci eu. Et netus et malesuada fames ac. Euismod lacinia at quis risus sed vulputate odio ut enim. In cursus turpis massa tincidunt dui ut ornare lectus. A pellentesque sit amet porttitor eget dolor. Senectus et netus et malesuada fames. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Sed elementum tempus egestas sed sed. Mauris pharetra et ultrices neque ornare aenean euismod. Consequat interdum varius sit amet mattis vulputate. Cursus turpis massa tincidunt dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Scelerisque in dictum non consectetur a erat nam. Pharetra pharetra massa massa ultricies mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Morbi blandit cursus risus at. Id faucibus nisl tincidunt eget. Mi quis hendrerit dolor magna. Eget arcu dictum varius duis. Aliquam eleifend mi in nulla. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Vitae tempus quam pellentesque nec nam aliquam. Placerat duis ultricies lacus sed turpis tincidunt. Condimentum mattis pellentesque id nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Viverra suspendisse potenti nullam ac tortor vitae. Mattis nunc sed blandit libero volutpat sed cras ornare. Malesuada fames ac turpis egestas. Et ultrices neque ornare aenean euismod elementum nisi. Egestas sed sed risus pretium quam vulputate. Eget nunc scelerisque viverra mauris. Nisi vitae suscipit tellus mauris. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. A diam sollicitudin tempor id eu nisl nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Felis bibendum ut tristique et egestas quis ipsum. Magna eget est lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel. Faucibus pulvinar elementum integer enim neque volutpat ac. Sit amet dictum sit amet justo donec enim diam.`
        }
      ]
    };
  }
};
</script>
<style lang="scss" scoped>
.full {
  text-align: justify;
  text-justify: inter-word;
}
</style>
